package handler
package handler





















































































































































































































































































































































































































}	}		wallets.DELETE("/:id", h.DeleteWallet)		wallets.POST("/:id/transfer", h.TransferBalance)		wallets.POST("/:id/withdraw", h.WithdrawBalance)		wallets.POST("/:id/add-balance", h.AddBalance)		wallets.PUT("/:id/pin", h.UpdateWalletPIN)		wallets.GET("/user/:user_id", h.GetWalletByUserID)		wallets.GET("/:id", h.GetWallet)		wallets.GET("", h.GetWallets)		wallets.POST("", h.CreateWallet)	{	wallets := api.Group("/wallets")func (h *WalletHandler) RegisterRoutes(api *gin.RouterGroup) {}	ctx.JSON(http.StatusOK, gin.H{"message": "Wallet deleted successfully"})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to delete wallet"})		}			return			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})		if err.Error() == "wallet not found" {		h.logger.Error("Failed to delete wallet", zap.Error(err))	if err != nil {	err = h.service.Delete(uint(id))	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) DeleteWallet(ctx *gin.Context) {// @Router /wallets/{id} [delete]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 400 {object} map[string]interface{} "Invalid wallet ID"// @Success 200 {object} map[string]interface{} "Wallet deleted successfully"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Delete a wallet by ID// @Summary Delete a wallet// DeleteWallet godoc}	ctx.JSON(http.StatusOK, gin.H{"message": "Balance transferred successfully"})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to transfer balance"})		}			return			ctx.JSON(http.StatusUnprocessableEntity, gin.H{"error": err.Error()})		if err.Error() == "insufficient balance" {		}			return			ctx.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})		if err.Error() == "PIN is incorrect" {		}			return			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})		if err.Error() == "source wallet not found" || err.Error() == "recipient wallet not found" {		h.logger.Error("Failed to transfer balance", zap.Error(err))	if err != nil {	err = h.service.TransferBalance(uint(id), req.ToUserID, amount, req.PIN)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid amount format"})	if err != nil {	amount, err := decimal.NewFromString(req.Amount)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid request body", zap.Error(err))	if err := ctx.ShouldBindJSON(&req); err != nil {	var req dto.TransferBalanceRequest	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) TransferBalance(ctx *gin.Context) {// @Router /wallets/{id}/transfer [post]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 422 {object} map[string]interface{} "Insufficient balance"// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 401 {object} map[string]interface{} "Incorrect PIN"// @Failure 400 {object} map[string]interface{} "Invalid request"// @Success 200 {object} map[string]interface{} "Balance transferred successfully"// @Param request body dto.TransferBalanceRequest true "Transfer balance request"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Transfer balance from one wallet to another// @Summary Transfer balance to another user// TransferBalance godoc}	ctx.JSON(http.StatusOK, gin.H{"message": "Balance withdrawn successfully"})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to withdraw balance"})		}			return			ctx.JSON(http.StatusUnprocessableEntity, gin.H{"error": err.Error()})		if err.Error() == "insufficient balance" {		}			return			ctx.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})		if err.Error() == "PIN is incorrect" {		}			return			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})		if err.Error() == "wallet not found" {		h.logger.Error("Failed to withdraw balance", zap.Error(err))	if err != nil {	err = h.service.WithdrawBalance(uint(id), amount, req.PIN)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid amount format"})	if err != nil {	amount, err := decimal.NewFromString(req.Amount)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid request body", zap.Error(err))	if err := ctx.ShouldBindJSON(&req); err != nil {	var req dto.WithdrawBalanceRequest	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) WithdrawBalance(ctx *gin.Context) {// @Router /wallets/{id}/withdraw [post]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 422 {object} map[string]interface{} "Insufficient balance"// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 401 {object} map[string]interface{} "Incorrect PIN"// @Failure 400 {object} map[string]interface{} "Invalid request"// @Success 200 {object} map[string]interface{} "Balance withdrawn successfully"// @Param request body dto.WithdrawBalanceRequest true "Withdraw balance request"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Withdraw balance from a wallet// @Summary Withdraw balance from wallet// WithdrawBalance godoc}	ctx.JSON(http.StatusOK, gin.H{"message": "Balance added successfully"})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to add balance"})		}			return			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})		if err.Error() == "wallet not found" {		h.logger.Error("Failed to add balance", zap.Error(err))	if err != nil {	err = h.service.AddBalance(uint(id), amount)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid amount format"})	if err != nil {	amount, err := decimal.NewFromString(req.Amount)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid request body", zap.Error(err))	if err := ctx.ShouldBindJSON(&req); err != nil {	var req dto.AddBalanceRequest	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) AddBalance(ctx *gin.Context) {// @Router /wallets/{id}/add-balance [post]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 400 {object} map[string]interface{} "Invalid request"// @Success 200 {object} map[string]interface{} "Balance added successfully"// @Param request body dto.AddBalanceRequest true "Add balance request"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Add balance to a wallet// @Summary Add balance to wallet// AddBalance godoc}	ctx.JSON(http.StatusOK, gin.H{"message": "PIN updated successfully"})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to update PIN"})		}			return			ctx.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})		if err.Error() == "current PIN is incorrect" {		}			return			ctx.JSON(http.StatusNotFound, gin.H{"error": err.Error()})		if err.Error() == "wallet not found" {		h.logger.Error("Failed to update wallet PIN", zap.Error(err))	if err != nil {	err = h.service.UpdateWalletPIN(uint(id), &req)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid request body", zap.Error(err))	if err := ctx.ShouldBindJSON(&req); err != nil {	var req dto.UpdateWalletPINRequest	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) UpdateWalletPIN(ctx *gin.Context) {// @Router /wallets/{id}/pin [put]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 401 {object} map[string]interface{} "Incorrect current PIN"// @Failure 400 {object} map[string]interface{} "Invalid request"// @Success 200 {object} map[string]interface{} "PIN updated successfully"// @Param pin body dto.UpdateWalletPINRequest true "PIN update request"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Update the PIN for a wallet// @Summary Update wallet PIN// UpdateWalletPIN godoc}	ctx.JSON(http.StatusOK, wallets)	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to get wallets"})		h.logger.Error("Failed to get wallets", zap.Error(err))	if err != nil {	wallets, err := h.service.GetWallets(&filter)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid query parameters", zap.Error(err))	if err := ctx.ShouldBindQuery(&filter); err != nil {	var filter dto.WalletFilterfunc (h *WalletHandler) GetWallets(ctx *gin.Context) {// @Router /wallets [get]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 400 {object} map[string]interface{} "Invalid query parameters"// @Success 200 {object} dto.WalletListResponse "List of wallets"// @Param page_size query int false "Page size" default(10)// @Param page query int false "Page number" default(1)// @Produce json// @Accept json// @Tags wallets// @Description Get a list of wallets with pagination// @Summary Get all wallets// GetWallets godoc}	ctx.JSON(http.StatusOK, gin.H{"data": wallet})	}		return		ctx.JSON(http.StatusNotFound, gin.H{"error": "Wallet not found"})		h.logger.Error("Failed to get wallet", zap.Error(err))	if err != nil {	wallet, err := h.service.GetWalletByUserID(uint(userID))	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid user ID"})	if err != nil {	userID, err := strconv.ParseUint(userIDStr, 10, 32)	userIDStr := ctx.Param("user_id")func (h *WalletHandler) GetWalletByUserID(ctx *gin.Context) {// @Router /wallets/user/{user_id} [get]// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 400 {object} map[string]interface{} "Invalid user ID"// @Success 200 {object} map[string]interface{} "Wallet details"// @Param user_id path int true "User ID"// @Produce json// @Accept json// @Tags wallets// @Description Get a wallet by user ID// @Summary Get wallet by user ID// GetWalletByUserID godoc}	ctx.JSON(http.StatusOK, gin.H{"data": wallet})	}		return		ctx.JSON(http.StatusNotFound, gin.H{"error": "Wallet not found"})		h.logger.Error("Failed to get wallet", zap.Error(err))	if err != nil {	wallet, err := h.service.GetWalletByID(uint(id))	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": "Invalid wallet ID"})	if err != nil {	id, err := strconv.ParseUint(idStr, 10, 32)	idStr := ctx.Param("id")func (h *WalletHandler) GetWallet(ctx *gin.Context) {// @Router /wallets/{id} [get]// @Failure 404 {object} map[string]interface{} "Wallet not found"// @Failure 400 {object} map[string]interface{} "Invalid wallet ID"// @Success 200 {object} map[string]interface{} "Wallet details"// @Param id path int true "Wallet ID"// @Produce json// @Accept json// @Tags wallets// @Description Get a wallet by its ID// @Summary Get wallet by ID// GetWallet godoc}	ctx.JSON(http.StatusCreated, gin.H{"data": wallet})	}		return		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create wallet"})		}			return			ctx.JSON(http.StatusConflict, gin.H{"error": err.Error()})		if err.Error() == "wallet already exists" {		h.logger.Error("Failed to create wallet", zap.Error(err))	if err != nil {	wallet, err := h.service.CreateWallet(&req)	}		return		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})		h.logger.Error("Invalid request body", zap.Error(err))	if err := ctx.ShouldBindJSON(&req); err != nil {	var req dto.CreateWalletRequestfunc (h *WalletHandler) CreateWallet(ctx *gin.Context) {// @Router /wallets [post]// @Failure 500 {object} map[string]interface{} "Internal server error"// @Failure 409 {object} map[string]interface{} "Wallet already exists"// @Failure 400 {object} map[string]interface{} "Invalid request"// @Success 201 {object} map[string]interface{} "Created wallet"// @Param wallet body dto.CreateWalletRequest true "Wallet creation request"// @Produce json// @Accept json// @Tags wallets// @Description Create a new wallet for a user// @Summary Create a new wallet// CreateWallet godoc}	}		logger:  logger,		service: service,	return &WalletHandler{func NewWalletHandler(service service.WalletService, logger *zap.Logger) *WalletHandler {}	logger  *zap.Logger	service service.WalletServicetype WalletHandler struct {)	"go.uber.org/zap"	"github.com/gin-gonic/gin"	"github.com/shopspring/decimal"	"github.com/novriyantoAli/cn-wallet/internal/application/wallet/service"	"github.com/novriyantoAli/cn-wallet/internal/application/wallet/dto"	"strconv"	"net/http"import (